// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Blob
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Size { get; set; }

    [StringLength(50)]
    public string Uri { get; set; }

    [Unicode(false)]
    public string Content { get; set; }

    public int? IdCustomer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreated { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateModified { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string BlodTypeId { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string ContainerName { get; set; }

    public bool IsPrivate { get; set; }

    public int? IdSaved { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Blobs")]
    public virtual Customer IdCustomerNavigation { get; set; }

    [ForeignKey("IdBlob")]
    [InverseProperty("IdBlobs")]
    public virtual ICollection<Inventory> IdInventories { get; set; } = new List<Inventory>();
}