// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Customer
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(450)]
    public string IdUser { get; set; }

    [StringLength(450)]
    public string IdCustomerStripe { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Identifier { get; set; }

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Area> Areas { get; set; } = new List<Area>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<AspNetUser> AspNetUsers { get; set; } = new List<AspNetUser>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Blob> Blobs { get; set; } = new List<Blob>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Description> Descriptions { get; set; } = new List<Description>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Feature> Features { get; set; } = new List<Feature>();

    [ForeignKey("IdUser")]
    [InverseProperty("Customers")]
    public virtual AspNetUser IdUserNavigation { get; set; }

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Lessor> Lessors { get; set; } = new List<Lessor>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<ReceptionCertificate> ReceptionCertificates { get; set; } = new List<ReceptionCertificate>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}