// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Feature
{
    [Key]
    public int Id { get; set; }

    public int? IdCustomer { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Features")]
    public virtual Customer IdCustomerNavigation { get; set; }

    [InverseProperty("IdFeatureNavigation")]
    public virtual ICollection<InventoryFeatureDescription> InventoryFeatureDescriptions { get; set; } = new List<InventoryFeatureDescription>();

    [ForeignKey("IdFeature")]
    [InverseProperty("IdFeatures")]
    public virtual ICollection<Description> IdDescriptions { get; set; } = new List<Description>();

    [ForeignKey("IdFeature")]
    [InverseProperty("IdFeatures")]
    public virtual ICollection<Service> IdServices { get; set; } = new List<Service>();
}