// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class InventoryFeatureDescription
{
    [Key]
    public int Id { get; set; }

    public int? IdInventory { get; set; }

    public int? IdFeature { get; set; }

    public int? IdDescription { get; set; }

    [StringLength(50)]
    public string DescriptionText { get; set; }

    [ForeignKey("IdDescription")]
    [InverseProperty("InventoryFeatureDescriptions")]
    public virtual Description IdDescriptionNavigation { get; set; }

    [ForeignKey("IdFeature")]
    [InverseProperty("InventoryFeatureDescriptions")]
    public virtual Feature IdFeatureNavigation { get; set; }

    [ForeignKey("IdInventory")]
    [InverseProperty("InventoryFeatureDescriptions")]
    public virtual Inventory IdInventoryNavigation { get; set; }
}