// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Property
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    public int? IdLessor { get; set; }

    public int? IdCustomer { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Suburb { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string District { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    public int? RoomsNumber { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? SurfaceArea { get; set; }

    public int? IdPropertyType { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string InteriorNumber { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string State { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Properties")]
    public virtual Customer IdCustomerNavigation { get; set; }

    [ForeignKey("IdLessor")]
    [InverseProperty("Properties")]
    public virtual Lessor IdLessorNavigation { get; set; }

    [ForeignKey("IdPropertyType")]
    [InverseProperty("Properties")]
    public virtual PropertyType IdPropertyTypeNavigation { get; set; }

    [InverseProperty("IdPropertyNavigation")]
    public virtual ICollection<ReceptionCertificate> ReceptionCertificates { get; set; } = new List<ReceptionCertificate>();
}