// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Service
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? IdCustomer { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Services")]
    public virtual Customer IdCustomerNavigation { get; set; }

    [InverseProperty("IdServiceNavigation")]
    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    [ForeignKey("IdService")]
    [InverseProperty("IdServices")]
    public virtual ICollection<Feature> IdFeatures { get; set; } = new List<Feature>();
}