// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Subscription
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string IdUser { get; set; }

    public int? IdCustomer { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Subscriptions")]
    public virtual Customer IdCustomerNavigation { get; set; }
}