// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

public partial class Tenant
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("RFC")]
    [StringLength(20)]
    [Unicode(false)]
    public string Rfc { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Addreess { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Suburb { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string District { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [StringLength(50)]
    public string EmailAddress { get; set; }

    [InverseProperty("IdTenantNavigation")]
    public virtual ICollection<ReceptionCertificate> ReceptionCertificates { get; set; } = new List<ReceptionCertificate>();
}