// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp2.Shared.Models;

[Table("Weatherforecast")]
public partial class Weatherforecast
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    public int? TemperatureC { get; set; }

    [StringLength(32)]
    [Unicode(false)]
    public string Summary { get; set; }

    public int? TemperatureF { get; set; }
}